
version: "3"

networks:
  default:

services:
  redis:
    image: redis:latest
    ports: 
      - "6379:6379"


  app:
    build: .
    image: darw1n167/backend:latest
    ports:  
      - "3001:3001"
    depends_on:
      - db
    environment:
      DATABASE_URL: $DATABASE_URL
      REDIS_URL: $REDIS_URL

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    depends_on:
      - redis
   
    
  frontend:
    build:
      context: ../iceberg
    image: darw1n167/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - app

volumes:
  db_data: